using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BUG : MonoBehaviour
{
    /*
        NOTE: THIS IS JUST A SIMPLE README DESCIRBING THE KNOWN BUG.

        1. WHEN ENEMY AND PLAYER BOTH TRY TO CONQUER THE NEUTRAL, WIERD THIGNS HAPPEN.

        2. ANOTHER BUG STORED IN MY LIKED VIDEO.

        3. USAGE OF QUEUE PROBABLY SHOULD CHANGED BC WHEN A BASE GOT CONQUERED
           DEQUEUE IS NOT ENOUGH TO HELP.
    */
}
